# This workflow will inititiave a Veracide Static Analysis Pipeline scan, return a results.json and convert to SARIF for upload as a code scanning alert

name: Veracode Static Analysis Pipeline Scan

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a job to build and submit pipeline scan, you will need to customize the build process accordingly and make sure the artifact you build is used as the file input to the pipeline scan file parameter
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
  
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
#    - uses: actions/upload-artifact@v4 # Copy files from repository to docker container so the next action can access them.
#      with:
#        path: target/verademo.war # Wildcards can be used to filter the files copied into the container. See: https://github.com/actions/upload-artifact

     # run the pipeline scan action
    - uses: wei/curl@master
      with:
        args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    - run: unzip -o pipeline-scan-LATEST.zip
    
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
#    - run: java -Dpipeline.debug=true -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --fail_on_severity="Very High, High" --file "/home/runner/work/verademo/verademo/target/verademo.war"
    - run: java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_KEY}}" --fail_on_severity="Very High, High" --file "target/verademo.war"
      continue-on-error: true
#    - name: pipeline-scan action step
#      id: pipeline-scan
#      uses: veracode/Veracode-pipeline-scan-action@v1.0.12
#      with:
#        vid: ${{ secrets.VERACODE_API_ID }}
#        vkey: ${{ secrets.VERACODE_API_KEY }}
#        file: "target/verademo.war" 
#        veracode_policy_name: "VeraDemo Policy"
#        fail_build: false
  
    # This step will import the flaws from the step above
    - name: import flaws as issues
      uses: veracode/veracode-flaws-to-issues@v2.1.19
      with:
        scan-results-json: 'results.json'
